  link:
    image: fractalnetworks/gateway-client:latest
    environment:
      LINK_DOMAIN: ${LINK_DOMAIN}
      EXPOSE: ${EXPOSE}
      GATEWAY_CLIENT_WG_PRIVKEY: ${WG_PRIVKEY}
      GATEWAY_LINK_WG_PUBKEY: ${GATEWAY_LINK_WG_PUBKEY}
      GATEWAY_ENDPOINT: ${GATEWAY_ENDPOINT}
    cap_add:
      - NET_ADMIN
